name: brc_pytorch
dependencies:
  - python>=3.7,<3.8
  - pip>=19.1
  - pip:
    - numpy>=1.14.3
    - torch>=1.3.0
    # data analysis
    - matplotlib>=3.1.1
    - seaborn>=0.9.0
    # dev tools
    - pytest==5.4.2
