---
name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          python-version: 3.8
      - name: Install dependencies and test installation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
          python -c "import brc_pytorch"

      - name: Test & coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest -s --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        continue-on-error: true
        with:
          fail_ci_if_error: true